---
- hosts: localhost

  vars:
    homebrew_list:
    - "cask"
    - "tmux"
    - "neomutt"
    - "aspell"
    - "git"
    - "wget"
    - "dockutil"
    - "m-cli"

    tap_list:
    - "caskroom/drivers"
    
    app_list:
    - "adium"
    - "google-chrome"
    - "iterm2"
    - "libreoffice"
    - "spectacle"
    - "keepassxc"
    - "virtualbox"
    - "virtualbox-extension-pack"
    - "vagrant"
    - "gpgtools"
    - "opensc"
    - "viscosity"
    - "yubikey-neo-manager"
    - "yubikey-personalization-gui"
    - "yubikey-piv-manager"
    - "spotify"
    - "wireshark"
    - "macvim"
    - "xquartz"
    - "macports"
    - "blockblock"
#    - "LyX"

  tasks:
    - name: Install homebrew packages
      homebrew: name="{{item}}" state="present"
      become: "false"
      with_items: "{{homebrew_list}}"
      tags:
      - "homebrew"

    - name: Install caskroom drivers
      homebrew_tap: name="{{item}}" state="present"
      become: "false"
      with_items: "{{tap_list}}"
      tags:
      - "apps"

    - name: custom cask files
      copy: src="files/cask/opensc.rb" dest="/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/opensc.rb"
      tags:
      - "apps"

    - name: Install apps
      homebrew_cask: name="{{item}}" state="present"
      become: "false"
      with_items: "{{app_list}}"
      tags:
      - "apps"

    - name: create config dir for Spectacle
      file: path="~/Library/Application Support/Spectacle/" state="directory"
      become: "false"
      tags:
      - "apps"

    - name: copy Spectacle shortcuts
      copy: src="files/spectacle/Shortcuts.json" dest="~/Library/Application Support/Spectacle/Shortcuts.json"
      become: "false"
      tags:
      - "apps"

    - name: Remove all items from the Dock
      become: "false"
      shell: /usr/local/bin/dockutil --remove all
      tags:
      - "dock"

    - name: Set the default Dock items
      become: "false"
      shell: "/usr/local/bin/dockutil --add {{ item }} --no-restart"
      with_items:
        - '/Applications/Calendar.app'
        - '/Applications/Google\ Chrome.app'
        - '/Applications/Adium.app'
      tags:
      - "dock"
    - name: Sets Downloads folder and restarts dock
      become: "false"
      shell: "/usr/local/bin/dockutil --add ~/Downloads --section others"
      tags:
      - "dock"

    - name: Prevent the system from sleeping
      shell: "systemsetup -setcomputersleep Off"
      tags:
      - "system"

    - name: Disable the sound effects on boot
      shell: nvram SystemAudioVolume=" "
      tags:
      - "system"

    - name: don't save to icloud by default
      shell: defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
      tags:
      - "system"

    - name: disable natural scrolling
      shell: defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false
      tags:
      - "system"

    - name: Ask for password when screensaver starts
      shell: defaults write com.apple.screensaver askForPassword -int 1
      tags:
      - "system"

    - name: Ask for password when screensaver starts. Delay
      shell: defaults write com.apple.screensaver askForPasswordDelay -int 0
      tags:
      - "system"

    - name: Don't write .DS_Store files on network volumes
      shell: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
      tags:
      - "system"

    - name: Don't write .DS_Store files on USB volumes
      shell: defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
      tags:
      - "system"
