---
- hosts: localhost

  vars:
    homebrew_list:
    - "cask"
    - "tmux"
    - "neomutt"
    - "git"
    - "wget"
    - "dockutil"
    - "m-cli"
    
    app_list:
    - "adium"
    - "google-chrome"
    - "iterm2"
    - "libreoffice"
    - "spectacle"
    - "keepassxc"
    - "virtualbox"
    - "virtualbox-extension-pack"
    - "vagrant"
    - "gpgtools"
    - "opensc"
    - "viscosity"
    - "yubikey-neo-manager"
    - "yubikey-personalization-gui"
    - "yubikey-piv-manager"
    - "spotify"
    - "LyX"
    - "wireshark"
    - "macvim"

  tasks:
    - name: Install homebrew packages
      homebrew: name="{{item}}" state="present"
      become: "false"
      with_items: "{{homebrew_list}}"
      tags:
      - "homebrew"

    - name: custom cask files
      copy: src="files/cask/opensc.rb" dest="/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/opensc.rb"
      tags:
      - "apps"

    - name: Install apps
      homebrew_cask: name="{{item}}" state="present"
      become: "false"
      with_items: "{{app_list}}"
      tags:
      - "apps"


    - name: copy Spectacle shortcuts
      copy: src="files/spectacle/Shortcuts.json" dest="~/Library/Application Support/Spectacle/Shortcuts.json"
      become: "false"

    - name: Remove all items from the Dock
      become: "false"
      shell: /usr/local/bin/dockutil --remove all
      tags:
      - "dock"

    - name: Set the default Dock items
      become: "false"
      shell: "/usr/local/bin/dockutil --add {{ item }} --no-restart"
      with_items:
        - '/Applications/Calendar.app'
        - '/Applications/Google\ Chrome.app'
        - '/Applications/Adium.app'
      tags:
      - "dock"
    - name: Sets Downloads folder and restarts dock
      become: "false"
      shell: "/usr/local/bin/dockutil --add ~/Downloads --section others"
      tags:
      - "dock"

    - name: Prevent the system from sleeping
      shell: "systemsetup -setcomputersleep Off"
      tags:
      - "system"

    - name: Disable the sound effects on boot
      shell: nvram SystemAudioVolume=" "
      tags:
      - "system"

    - name: don't save to icloud by default
      osx_defaults: domain="NSGlobalDomain" key="NSDocumentSaveNewDocumentsToCloud" type="bool" value="false" state="present"
      tags:
      - "system"
