#! /bin/sh
#
#
#     Copyright (C) 1998-2015  Roland Rosenfeld <roland@spinnaker.de>
#
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301,, USA.
#
# $Id: m_gpg.sh.in,v 1.27 2016/01/08 17:05:08 roland Exp $
#

m_gpg_query()
{
    GPG=`which gpg`

    if [ -x "$GPG" ]
    then
        args="$@"
        $GPG --no-auto-check-trustdb --list-keys --with-colons "$args" 2>/dev/null \
        | grep -a '^\(pub\|uid\):[^re]:\([^:]*:\)\{7,7\}[^<>:]* <[^<>@: ]*@[^<>@: ]*>[^<>@:]*:' \
        | sed -e 's/^\([^:]*:\)\{9,9\}\([^<:]*\) <\([^>:]*\)>.*:.*$/\3  \2      (GnuPG)/' \
        | sed -e 's/    \([^    ]\{27,27\}\)[^  ]*      /       \1...   /' \
        | grep -ia "$args" || :

    fi
}
